name: Build App for Windows and Ubuntu

on:
  workflow_dispatch:

jobs:
  # Job dla Ubuntu
  build_ubuntu:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          source venv/bin/activate
          pyinstaller --onefile --name "ModbusSniffer" modbus_sniffer_GUI.py

      - name: Upload Ubuntu build to release
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-build
          path: dist/ModbusSniffer

  # Job dla Windowsa
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          .\venv\Scripts\activate
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          .\venv\Scripts\activate
          pyinstaller --onefile --name "ModbusSniffer" --icon="./images/icon.ico" modbus_sniffer_GUI.py

      - name: Upload Windows build to release
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist\ModbusSniffer.exe
